name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LUA_LIB_NAME: lua
      LUA_LIB: ${{ github.workspace }}/lua/lua5.1/
      LUA_INC: ${{ github.workspace }}/lua/lua5.1/include

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Build with hot-reload feature
      run: cargo build --features hot-reload

    - name: Run tests
      run: cargo test

    - name: Check formatting
      run: cargo fmt -- --check
