name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Build
      run: cargo build

    - name: Build with hot-reload feature
      run: cargo build --features hot-reload

    - name: Run tests
      run: cargo test

    - name: Check formatting
      run: cargo fmt -- --check
